hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - datasz=100p
    - model=gbt
    - dataset=ABIDE
    - repeat_time=5
    - preprocess=mixup
  job:
    name: __main__
    chdir: null
    override_dirname: dataset=ABIDE,datasz=100p,model=gbt,preprocess=mixup,repeat_time=5
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: D:\1-Mine-GBT4clas
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: D:\1-Mine-GBT4clas\source\conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      preprocess: mixup
      datasz: 100p
      training: basic_training
      optimizer: adam
      model: gbt
      dataset: ABIDE
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
dataset:
  name: abide
  batch_size: 16
  test_batch_size: 16
  val_batch_size: 16
  train_set: 0.7
  val_set: 0.1
  path: ./source/data/abide.npy
  stratified: true
  drop_last: true
model:
  name: GeometricBrainTransformer
  sizes:
  - 360
  - 100
  pooling:
  - false
  - true
  pos_encoding: none
  orthogonal: true
  freeze_center: true
  project_assignment: true
  pos_embed_dim: 360
optimizer:
- name: Adam
  lr: 0.0001
  match_rule: None
  except_rule: None
  no_weight_decay: false
  weight_decay: 0.0001
  lr_scheduler:
    mode: cos
    base_lr: 0.0001
    target_lr: 1.0e-05
    decay_factor: 0.1
    milestones:
    - 0.3
    - 0.6
    - 0.9
    poly_power: 2.0
    lr_decay: 0.98
    warm_up_from: 0.0
    warm_up_steps: 0
training:
  name: Train
  epochs: 200
datasz:
  percentage: 1.0
preprocess:
  name: continus_mixup
  continus: true
repeat_time: 5
log_path: result
save_learnable_graph: false
